const $=s=>document.querySelector(s);let data;
async function api(path,body){const response=await fetch('/api/admin/'+path,{method:body?'POST':'GET',headers:body?{'Content-Type':'application/json'}:{},body:body?JSON.stringify(body):undefined});const result=await response.json();if(!response.ok){if(response.status===401){$('#login').hidden=false;$('#dashboard').hidden=true;}throw Error(result.message);}return result;}
function notice(text){$('#status').textContent=text;}
function el(tag,text){const e=document.createElement(tag);if(text!==undefined)e.textContent=text;return e;}
async function refresh(){try{data=await api('data');$('#login').hidden=true;$('#dashboard').hidden=false;$('#logout').hidden=false;$('#email-status').textContent=data.emailConfigured?'Email notifications connected.':'Email not connected. Requests still save here; notification delivery needs setup.';renderAppointments();renderTips();for(const k of ['text','button','link'])$('#banner-form').elements[k].value=data.banner[k];$('#banner-form').elements.enabled.checked=data.banner.enabled;$('#banner-form').elements.image.value=data.banner.image||'';$('#banner-preview').hidden=!data.banner.image;if(data.banner.image)$('#banner-preview').src=data.banner.image;}catch(e){notice(e.message);}}
$('#login').onsubmit=async event=>{event.preventDefault();try{await api('login',{password:event.target.elements.password.value});event.target.reset();notice('');await refresh();}catch(e){notice(e.message);}};
$('#logout').onclick=async()=>{await api('logout',{});location.reload();};$('#refresh').onclick=refresh;
document.querySelectorAll('[data-tab]').forEach(button=>button.onclick=()=>{document.querySelectorAll('.tab').forEach(s=>s.hidden=s.id!==button.dataset.tab);document.querySelectorAll('[data-tab]').forEach(b=>b.classList.toggle('active',b===button));});document.querySelector('[data-tab]').classList.add('active');
function renderAppointments(){const target=$('#appointment-list');target.replaceChildren();const q=$('#search').value.toLowerCase(),filter=$('#filter').value;const rows=data.appointments.filter(a=>(!filter||a.status===filter)&&(a.name.toLowerCase().includes(q)||a.phone.includes(q)));if(!rows.length)target.append(el('p','No appointments match. New requests will appear here.'));rows.forEach(a=>{const card=el('article');card.className='appointment';const top=el('div');top.className='appointment-top';top.append(el('h3',a.name));const badge=el('span',a.status);badge.className='badge';top.append(badge);card.append(top,el('p',`${a.date} · ${a.time} IST | Ref: ${a.id.slice(0,8)}`),el('p',`${a.phone} · ${a.email||'No email'}\n${a.message||'No message'}\nEmail notification: ${a.emailStatus}`));const controls=el('div');controls.className='appointment-controls';const select=el('select');select.setAttribute('aria-label','Appointment status');['pending','confirmed','cancelled','completed'].forEach(s=>{const o=el('option',s);o.value=s;select.append(o);});select.value=a.status;const notes=el('textarea');notes.value=a.notes;notes.placeholder='Internal notes';notes.setAttribute('aria-label','Internal notes');const save=el('button','Save status');save.onclick=async()=>{save.disabled=true;try{await api('appointment',{id:a.id,status:select.value,notes:notes.value});notice('Appointment updated. Contact the patient to notify them.');await refresh();}catch(e){notice(e.message);}finally{save.disabled=false;}};controls.append(select,notes,save);card.append(controls);target.append(card);});}
$('#search').oninput=renderAppointments;$('#filter').onchange=renderAppointments;
$('#banner-form').onsubmit=async e=>{e.preventDefault();try{const d=Object.fromEntries(new FormData(e.target));d.enabled=e.target.elements.enabled.checked;await api('banner',d);notice('Mobile banner saved. Refresh the website to see it.');await refresh();}catch(e){notice(e.message);}};
function renderTips(){const target=$('#tip-list');target.replaceChildren();data.tips.forEach(t=>{const card=el('article');card.className='panel';card.append(el('h2',t.title),el('p',t.description),el('p',t.published?'Published':'Unpublished'));const edit=el('button','Edit tip');edit.onclick=()=>{const f=$('#tip-form');for(const k of ['id','title','description','image','url'])f.elements[k].value=t[k];f.elements.published.checked=t.published;$('#tip-form-title').textContent='Edit Health Tip';f.scrollIntoView({behavior:'smooth'});};card.append(edit);target.append(card);});}
$('#tip-form').onsubmit=async e=>{e.preventDefault();try{const d=Object.fromEntries(new FormData(e.target));d.published=e.target.elements.published.checked;await api('tip',d);e.target.reset();e.target.elements.id.value='';notice('Health Tip saved.');await refresh();}catch(e){notice(e.message);}};$('#new-tip').onclick=()=>{$('#tip-form').reset();$('#tip-form').elements.id.value='';$('#tip-form-title').textContent='Add a Health Tip';};refresh();
$('#tip-upload').addEventListener('change',async event=>{
 const file=event.target.files[0];if(!file)return;
 const status=$('#upload-status'),preview=$('#upload-preview');
 if(!['image/jpeg','image/png','image/webp'].includes(file.type)||file.size>5*1024*1024){status.textContent='Choose a JPG, PNG or WebP image under 5 MB.';event.target.value='';return;}
 const save=$('#tip-form button');save.disabled=true;event.target.disabled=true;status.textContent='Uploading photo…';
 try{
 const bitmap=await createImageBitmap(file);const scale=Math.min(1,1600/Math.max(bitmap.width,bitmap.height));const canvas=document.createElement('canvas');canvas.width=Math.max(1,Math.round(bitmap.width*scale));canvas.height=Math.max(1,Math.round(bitmap.height*scale));canvas.getContext('2d').drawImage(bitmap,0,0,canvas.width,canvas.height);bitmap.close();
 const encoded=canvas.toDataURL('image/png').split(',')[1];const result=await api('upload',{data:encoded});$('#tip-form').elements.image.value=result.url;preview.src=result.url;preview.hidden=false;status.textContent='Photo uploaded. Save the Health Tip to use it on the website.';
 }catch(e){status.textContent=e.message||'Upload failed. Please try another photo.';}finally{save.disabled=false;event.target.disabled=false;event.target.value='';}
});
$('#tip-form').addEventListener('reset',()=>{$('#upload-preview').hidden=true;$('#upload-status').textContent='';});
$('#banner-upload').addEventListener('change',async event=>{
 const file=event.target.files[0];if(!file)return;
 const status=$('#banner-upload-status'),preview=$('#banner-preview');
 if(!['image/jpeg','image/png','image/webp'].includes(file.type)||file.size>5*1024*1024){status.textContent='Choose a JPG, PNG or WebP image under 5 MB.';event.target.value='';return;}
 const save=$('#banner-form button:not([type="button"])');save.disabled=true;event.target.disabled=true;status.textContent='Uploading banner…';
 try{const bitmap=await createImageBitmap(file);const scale=Math.min(1,1600/Math.max(bitmap.width,bitmap.height));const canvas=document.createElement('canvas');canvas.width=Math.max(1,Math.round(bitmap.width*scale));canvas.height=Math.max(1,Math.round(bitmap.height*scale));canvas.getContext('2d').drawImage(bitmap,0,0,canvas.width,canvas.height);bitmap.close();const result=await api('upload',{data:canvas.toDataURL('image/png').split(',')[1]});$('#banner-form').elements.image.value=result.url;preview.src=result.url;preview.hidden=false;status.textContent='Image uploaded. Click Save banner to publish.';}catch(e){status.textContent=e.message||'Upload failed.';}finally{save.disabled=false;event.target.disabled=false;event.target.value='';}
});
$('#remove-banner-image').onclick=()=>{$('#banner-form').elements.image.value='';$('#banner-preview').hidden=true;$('#banner-upload-status').textContent='Image removed from this draft. Click Save banner to apply.';};
