const fs=require('fs');let s=fs.readFileSync('booking.js','utf8');const start=s.indexOf("visitDate.addEventListener('input'");const end=s.indexOf('visitForm.elements.phone',start);s=s.slice(0,start)+`const validateVisitDay = () => {
  visitDate.min = localToday();
  const sunday = visitDate.value && new Date(visitDate.value+'T12:00:00').getDay() === 0;
  visitDate.setCustomValidity(sunday ? 'The clinic is closed on Sunday. Please choose Monday to Saturday.' : '');
  document.querySelector('#visit-day').textContent = sunday ? 'Sunday closed — choose another date' : visitDate.value ? new Date(visitDate.value+'T12:00:00').toLocaleDateString('en-IN',{weekday:'long'}) : 'Monday–Saturday · Sunday closed';
};
visitDate.addEventListener('input', validateVisitDay);
`+s.slice(end);s=s.replace('if(!visitForm.reportValidity())','validateVisitDay();\n  if(!visitForm.reportValidity())');fs.writeFileSync('booking.js',s);
const files=['index.html','about-us.html','contact.html','apply-site-details.js',...fs.readdirSync('.',{withFileTypes:true}).filter(e=>e.isDirectory()&&e.name.endsWith('-durg-bhilai')).map(e=>e.name+'/index.html')];for(const f of files){let h=fs.readFileSync(f,'utf8');h=h.replaceAll('Call to confirm timings and appointment availability before your visit.','Monday–Saturday · Sunday closed. Call to confirm timings and appointment availability before your visit.').replaceAll('Call before travelling to confirm consultation timings.','Sunday closed. Call before travelling to confirm consultation timings.').replace('aria-label="7 days"','aria-label="6 days"').replace('data-count="7" aria-hidden="true">7','data-count="6" aria-hidden="true">6').replace('Here for your skin, every day of the week.','Monday to Saturday. Closed on Sundays.').replace('<span>Consultation timings</span>','<span>Monday–Saturday<br>Sunday closed</span>').replace('Choose your preferred day','Monday–Saturday · Sunday closed').replace('Please call the clinic to confirm current timings and appointment availability before travelling.','The clinic is closed on Sundays. Please call to confirm Monday–Saturday consultation timings and appointment availability before travelling.');fs.writeFileSync(f,h);}
