module.exports = [
  {
    slug: 'pimple-treatment-durg-bhilai',
    name: 'Pimple Treatment',
    image: 'pimple-treatment-durg-bhilai.jpg',
    intro: 'Personalised dermatology guidance for active pimples, breakouts and recurring acne.',
    sections: [
      ['Who it may help', ['Active pimples and recurring breakouts', 'Blackheads, whiteheads and clogged pores', 'Acne that leaves marks or affects confidence']],
      ['What to expect', 'Your dermatologist will assess your skin, acne pattern and triggers before discussing a suitable treatment plan.'],
    ],
    faq: [['Can acne be treated permanently?', 'Acne can usually be controlled with a consistent, personalised plan. Results and maintenance needs vary by person.']],
    medicalSource: ['American Academy of Dermatology: Acne', 'https://www.aad.org/public/diseases/acne'],
  },
  {
    slug: 'acne-scar-treatment-durg-bhilai',
    name: 'Acne Scar Treatment',
    image: 'acne-scar-treatment-durg-bhilai.jpg',
    intro: 'Explore options for acne marks, uneven texture and scars after a clinical skin assessment.',
    sections: [['Treatment planning', 'The right approach depends on scar type, skin tone, active acne and your goals. A consultation helps set realistic expectations.']],
    faq: [['When should I treat acne scars?', 'Active acne is often addressed first, followed by a scar plan suited to your skin and healing response.']],
    medicalSource: ['American Academy of Dermatology: Acne scars', 'https://www.aad.org/public/diseases/acne/derm-treat/scars/treatment'],
  },
  {
    slug: 'dark-circle-treatment-durg-bhilai',
    name: 'Dark Circle Treatment',
    image: 'dark-circle-treatment-durg-bhilai.jpg',
    intro: 'Understand the possible causes of under-eye darkness and discuss appropriate care.',
    sections: [['A personalised approach', 'Dark circles may relate to pigmentation, visible vessels, shadows, thin skin or tired-looking eyes. Your dermatologist can help identify contributing factors.']],
    faq: [['What causes dark circles?', 'Several factors can contribute, including genetics, pigmentation, allergies, sleep and natural changes around the eyes.']],
  },
  {
    slug: 'pigmentation-dark-spots-treatment-durg-bhilai',
    name: 'Dark Spots & Pigmentation Treatment',
    image: 'pigmentation-dark-spots-treatment-durg-bhilai.jpg',
    intro: 'Discuss uneven tone, dark spots and pigmentation with a dermatologist-led assessment.',
    sections: [['Care for uneven tone', 'Treatment depends on the cause and may include daily sun protection and a tailored topical or in-clinic plan.']],
    faq: [['Will pigmentation come back?', 'Pigmentation can recur, especially with sun exposure or ongoing triggers, so maintenance and sun protection are important.']],
    medicalSource: ['American Academy of Dermatology: Melasma', 'https://www.aad.org/public/diseases/a-z/melasma-overview'],
  },
  {
    slug: 'hair-loss-alopecia-treatment-durg-bhilai',
    name: 'Hair Loss & Alopecia Treatment',
    image: 'hair-loss-alopecia-treatment-durg-bhilai.jpg',
    intro: 'Get a structured assessment for hair fall, thinning and changes in the scalp.',
    sections: [['Understanding hair loss', 'Hair loss has many possible causes. A consultation helps review the pattern, timeline and relevant health factors before planning care.']],
    faq: [['When should I consult for hair loss?', 'Early assessment can help identify treatable causes and set realistic expectations for regrowth or stabilisation.']],
    medicalSource: ['American Academy of Dermatology: Hair loss', 'https://www.aad.org/public/diseases/hair-loss'],
  },
  {
    slug: 'laser-hair-reduction-durg-bhilai',
    name: 'Laser Hair Reduction',
    image: 'laser-hair-reduction-durg-bhilai.jpg',
    intro: 'Learn whether laser hair reduction may be suitable for your hair and skin type.',
    sections: [['What to expect', 'Laser hair reduction is planned over multiple sessions because hair grows in cycles. Suitability, settings and expected results are discussed during consultation.']],
    faq: [['Is laser hair reduction permanent?', 'It can provide long-term reduction, but results vary and maintenance sessions may be needed.']],
    medicalSource: ['American Academy of Dermatology: Laser hair removal', 'https://www.aad.org/public/cosmetic/hair-removal/laser-hair-removal-faqs'],
  },
];
